module Cloudpayments
  module Resources
    class Store
      class Orders
        def create: (
          ?id: Integer,
          ?complete: bool,
          ?pet_id: Integer,
          ?quantity: Integer,
          ?ship_date: Time,
          ?status: Cloudpayments::Models::Order::status,
          ?request_options: Cloudpayments::request_opts
        ) -> Cloudpayments::Order

        def retrieve: (
          Integer order_id,
          ?request_options: Cloudpayments::request_opts
        ) -> Cloudpayments::Order

        def delete: (
          Integer order_id,
          ?request_options: Cloudpayments::request_opts
        ) -> nil

        def initialize: (client: Cloudpayments::Client) -> void
      end
    end
  end
end
