module Cloudpayments
  module Models
    type order_cancel_params =
      { id: String } & Cloudpayments::Internal::Type::request_parameters

    class OrderCancelParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
