module Cloudpayments
  module Models
    type payment_post3ds_params =
      { pa_res: String, transaction_id: Integer }
      & Cloudpayments::Internal::Type::request_parameters

    class PaymentPost3dsParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_accessor pa_res: String

      attr_accessor transaction_id: Integer

      def initialize: (
        pa_res: String,
        transaction_id: Integer,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        pa_res: String,
        transaction_id: Integer,
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
