module Cloudpayments
  module Models
    type payment_refund_params =
      { amount: Float, transaction_id: Integer, json_data: top }
      & Cloudpayments::Internal::Type::request_parameters

    class PaymentRefundParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_accessor amount: Float

      attr_accessor transaction_id: Integer

      attr_reader json_data: top?

      def json_data=: (top) -> top

      def initialize: (
        amount: Float,
        transaction_id: Integer,
        ?json_data: top,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        amount: Float,
        transaction_id: Integer,
        json_data: top,
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
