module Cloudpayments
  module Models
    type pet_create_params =
      {  } & Cloudpayments::Internal::Type::request_parameters

    class PetCreateParams < Cloudpayments::Models::Pet
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      def initialize: (?request_options: Cloudpayments::request_opts) -> void

      def to_hash: -> { request_options: Cloudpayments::RequestOptions }
    end
  end
end
