module Cloudpayments
  module Models
    type pet_find_by_status_params =
      { status: Cloudpayments::Models::PetFindByStatusParams::status }
      & Cloudpayments::Internal::Type::request_parameters

    class PetFindByStatusParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_reader status: Cloudpayments::Models::PetFindByStatusParams::status?

      def status=: (
        Cloudpayments::Models::PetFindByStatusParams::status
      ) -> Cloudpayments::Models::PetFindByStatusParams::status

      def initialize: (
        ?status: Cloudpayments::Models::PetFindByStatusParams::status,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        status: Cloudpayments::Models::PetFindByStatusParams::status,
        request_options: Cloudpayments::RequestOptions
      }

      type status = :available | :pending | :sold

      module Status
        extend Cloudpayments::Internal::Type::Enum

        AVAILABLE: :available
        PENDING: :pending
        SOLD: :sold

        def self?.values: -> ::Array[Cloudpayments::Models::PetFindByStatusParams::status]
      end
    end
  end
end
