module Cloudpayments
  module Models
    type pet_find_by_tags_params =
      { tags: ::Array[String] }
      & Cloudpayments::Internal::Type::request_parameters

    class PetFindByTagsParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?tags: ::Array[String],
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        tags: ::Array[String],
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
