module Cloudpayments
  module Models
    type pet_upload_image_params =
      {
        image: Cloudpayments::Internal::file_input,
        additional_metadata: String
      }
      & Cloudpayments::Internal::Type::request_parameters

    class PetUploadImageParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_accessor image: Cloudpayments::Internal::file_input

      attr_reader additional_metadata: String?

      def additional_metadata=: (String) -> String

      def initialize: (
        image: Cloudpayments::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        image: Cloudpayments::Internal::file_input,
        additional_metadata: String,
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
