module Cloudpayments
  module Models
    type subscription_create_params =
      {
        account_id: String,
        amount: Float,
        currency: String,
        description: String,
        interval: String,
        period: Integer,
        require_confirmation: bool,
        start_date: Time,
        token: String,
        customer_receipt: top,
        email: String,
        max_periods: Integer
      }
      & Cloudpayments::Internal::Type::request_parameters

    class SubscriptionCreateParams < Cloudpayments::Internal::Type::BaseModel
      extend Cloudpayments::Internal::Type::RequestParameters::Converter
      include Cloudpayments::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor amount: Float

      attr_accessor currency: String

      attr_accessor description: String

      attr_accessor interval: String

      attr_accessor period: Integer

      attr_accessor require_confirmation: bool

      attr_accessor start_date: Time

      attr_accessor token: String

      attr_reader customer_receipt: top?

      def customer_receipt=: (top) -> top

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader max_periods: Integer?

      def max_periods=: (Integer) -> Integer

      def initialize: (
        account_id: String,
        amount: Float,
        currency: String,
        description: String,
        interval: String,
        period: Integer,
        require_confirmation: bool,
        start_date: Time,
        token: String,
        ?customer_receipt: top,
        ?email: String,
        ?max_periods: Integer,
        ?request_options: Cloudpayments::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        amount: Float,
        currency: String,
        description: String,
        interval: String,
        period: Integer,
        require_confirmation: bool,
        start_date: Time,
        token: String,
        customer_receipt: top,
        email: String,
        max_periods: Integer,
        request_options: Cloudpayments::RequestOptions
      }
    end
  end
end
