module Cloudpayments
  module Models
    type subscription_find_response =
      {
        success: bool,
        message: String,
        model: ::Array[Cloudpayments::Subscription]
      }

    class SubscriptionFindResponse < Cloudpayments::Internal::Type::BaseModel
      attr_accessor success: bool

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader model: ::Array[Cloudpayments::Subscription]?

      def model=: (
        ::Array[Cloudpayments::Subscription]
      ) -> ::Array[Cloudpayments::Subscription]

      def initialize: (
        success: bool,
        ?message: String,
        ?model: ::Array[Cloudpayments::Subscription]
      ) -> void

      def to_hash: -> {
        success: bool,
        message: String,
        model: ::Array[Cloudpayments::Subscription]
      }
    end
  end
end
