module Cloudpayments
  module Models
    type subscription_create_response =
      { success: bool, message: String, model: Cloudpayments::Subscription }

    class SubscriptionCreateResponse < Cloudpayments::Internal::Type::BaseModel
      attr_accessor success: bool

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader model: Cloudpayments::Subscription?

      def model=: (Cloudpayments::Subscription) -> Cloudpayments::Subscription

      def initialize: (
        success: bool,
        ?message: String,
        ?model: Cloudpayments::Subscription
      ) -> void

      def to_hash: -> {
        success: bool,
        message: String,
        model: Cloudpayments::Subscription
      }
    end
  end
end
