module Cloudpayments
  module Resources
    class Payments
      class Tokens
        def auth: (
          account_id: String,
          amount: Float,
          token: String,
          tr_initiator_code: Integer,
          ?currency: String,
          ?description: String,
          ?email: String,
          ?invoice_id: String,
          ?ip_address: String,
          ?json_data: top,
          ?payer: Cloudpayments::Payments::TokenAuthParams::Payer,
          ?payment_scheduled: Integer,
          ?request_options: Cloudpayments::request_opts
        ) -> Cloudpayments::Models::Payments::TokenAuthResponse

        def charge: (
          account_id: String,
          amount: Float,
          token: String,
          tr_initiator_code: Integer,
          ?currency: String,
          ?description: String,
          ?email: String,
          ?invoice_id: String,
          ?ip_address: String,
          ?json_data: top,
          ?payer: Cloudpayments::Payments::TokenChargeParams::Payer,
          ?payment_scheduled: Integer,
          ?request_options: Cloudpayments::request_opts
        ) -> Cloudpayments::Models::Payments::TokenChargeResponse

        def initialize: (client: Cloudpayments::Client) -> void
      end
    end
  end
end
