module Cloudpayments
  module Models
    module Store
      type order_retrieve_params =
        {  } & Cloudpayments::Internal::Type::request_parameters

      class OrderRetrieveParams < Cloudpayments::Internal::Type::BaseModel
        extend Cloudpayments::Internal::Type::RequestParameters::Converter
        include Cloudpayments::Internal::Type::RequestParameters

        def initialize: (?request_options: Cloudpayments::request_opts) -> void

        def to_hash: -> { request_options: Cloudpayments::RequestOptions }
      end
    end
  end
end
