module Cloudpayments
  module Resources
    class Pets
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Cloudpayments::Category,
        ?status: Cloudpayments::Models::Pet::status,
        ?tags: ::Array[Cloudpayments::Pet::Tag],
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Pet

      def retrieve: (
        Integer pet_id,
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Pet

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Cloudpayments::Category,
        ?status: Cloudpayments::Models::Pet::status,
        ?tags: ::Array[Cloudpayments::Pet::Tag],
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Pet

      def delete: (
        Integer pet_id,
        ?request_options: Cloudpayments::request_opts
      ) -> nil

      def find_by_status: (
        ?status: Cloudpayments::Models::PetFindByStatusParams::status,
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Models::pet_find_by_tags_response

      def update_by_id: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: Cloudpayments::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        image: Cloudpayments::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: Cloudpayments::request_opts
      ) -> Cloudpayments::Models::PetUploadImageResponse

      def initialize: (client: Cloudpayments::Client) -> void
    end
  end
end
