module CloudpaymentsRuby
  module Models
    type payment_auth_response =
      CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember0
      | CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1

    module PaymentAuthResponse
      extend CloudpaymentsRuby::Internal::Type::Union

      type union_member0 =
        {
          success: bool,
          message: String,
          model: CloudpaymentsRuby::Transaction
        }

      class UnionMember0 < CloudpaymentsRuby::Internal::Type::BaseModel
        attr_accessor success: bool

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader model: CloudpaymentsRuby::Transaction?

        def model=: (
          CloudpaymentsRuby::Transaction
        ) -> CloudpaymentsRuby::Transaction

        def initialize: (
          success: bool,
          ?message: String,
          ?model: CloudpaymentsRuby::Transaction
        ) -> void

        def to_hash: -> {
          success: bool,
          message: String,
          model: CloudpaymentsRuby::Transaction
        }
      end

      type union_member1 =
        {
          success: bool,
          message: String,
          model: CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model
        }

      class UnionMember1 < CloudpaymentsRuby::Internal::Type::BaseModel
        attr_accessor success: bool

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader model: CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model?

        def model=: (
          CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model
        ) -> CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model

        def initialize: (
          success: bool,
          ?message: String,
          ?model: CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model
        ) -> void

        def to_hash: -> {
          success: bool,
          message: String,
          model: CloudpaymentsRuby::Models::PaymentAuthResponse::UnionMember1::Model
        }

        type model =
          {
            acs_url: String,
            i_frame_is_allowed: bool,
            pa_req: String,
            three_ds_callback_id: String,
            transaction_id: Integer,
            escrow_accumulation_id: String,
            frame_height: Integer,
            frame_width: Integer,
            go_req: String,
            three_ds_session_data: String
          }

        class Model < CloudpaymentsRuby::Internal::Type::BaseModel
          attr_accessor acs_url: String

          attr_accessor i_frame_is_allowed: bool

          attr_accessor pa_req: String

          attr_accessor three_ds_callback_id: String

          attr_accessor transaction_id: Integer

          attr_reader escrow_accumulation_id: String?

          def escrow_accumulation_id=: (String) -> String

          attr_reader frame_height: Integer?

          def frame_height=: (Integer) -> Integer

          attr_reader frame_width: Integer?

          def frame_width=: (Integer) -> Integer

          attr_reader go_req: String?

          def go_req=: (String) -> String

          attr_reader three_ds_session_data: String?

          def three_ds_session_data=: (String) -> String

          def initialize: (
            acs_url: String,
            i_frame_is_allowed: bool,
            pa_req: String,
            three_ds_callback_id: String,
            transaction_id: Integer,
            ?escrow_accumulation_id: String,
            ?frame_height: Integer,
            ?frame_width: Integer,
            ?go_req: String,
            ?three_ds_session_data: String
          ) -> void

          def to_hash: -> {
            acs_url: String,
            i_frame_is_allowed: bool,
            pa_req: String,
            three_ds_callback_id: String,
            transaction_id: Integer,
            escrow_accumulation_id: String,
            frame_height: Integer,
            frame_width: Integer,
            go_req: String,
            three_ds_session_data: String
          }
        end
      end

      def self?.variants: -> ::Array[CloudpaymentsRuby::Models::payment_auth_response]
    end
  end
end
