module CloudpaymentsRuby
  module Models
    type subscription_cancel_response = { success: bool, message: String }

    class SubscriptionCancelResponse < CloudpaymentsRuby::Internal::Type::BaseModel
      attr_accessor success: bool

      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (success: bool, ?message: String) -> void

      def to_hash: -> { success: bool, message: String }
    end
  end
end
