module CloudpaymentsRuby
  module Models
    type transaction =
      {
        amount: Float,
        android_pay: bool,
        card_exp_date: String,
        card_first_six: String,
        card_holder_message: String,
        card_last_four: String,
        card_type: String,
        card_type_code: Integer,
        created_date: String,
        created_date_iso: String,
        culture_name: String,
        currency: String,
        currency_code: Integer,
        gateway_name: String,
        ip_address: String,
        ip_country: String,
        issuer: String,
        issuer_bank_country: String,
        payment_amount: Float,
        payment_currency: String,
        payment_currency_code: Integer,
        public_id: String,
        reason: String,
        reason_code: Integer,
        refunded: bool,
        status: String,
        status_code: Integer,
        terminal_url: String,
        test_mode: bool,
        total_fee: Float,
        transaction_id: Integer,
        type: Integer,
        wallet_type: String,
        account_id: String,
        auth_code: String,
        auth_date: String,
        auth_date_iso: String,
        card_category: String,
        card_product: String,
        confirm_date: String,
        confirm_date_iso: String,
        description: String,
        email: String,
        escrow_accumulation_id: String,
        fall_back_scenario_declined_transaction_id: Integer,
        invoice_id: String,
        ip_city: String,
        ip_district: String,
        ip_latitude: Float,
        ip_longitude: Float,
        ip_region: String,
        json_data: String,
        name: String,
        original_transaction_id: Integer,
        payout_amount: Float,
        payout_date: String,
        payout_date_iso: String,
        rrn: String,
        subscription_id: String,
        token: String
      }

    class Transaction < CloudpaymentsRuby::Internal::Type::BaseModel
      attr_accessor amount: Float

      attr_accessor android_pay: bool

      attr_accessor card_exp_date: String

      attr_accessor card_first_six: String

      attr_accessor card_holder_message: String

      attr_accessor card_last_four: String

      attr_accessor card_type: String

      attr_accessor card_type_code: Integer

      attr_accessor created_date: String

      attr_accessor created_date_iso: String

      attr_accessor culture_name: String

      attr_accessor currency: String

      attr_accessor currency_code: Integer

      attr_accessor gateway_name: String

      attr_accessor ip_address: String

      attr_accessor ip_country: String

      attr_accessor issuer: String

      attr_accessor issuer_bank_country: String

      attr_accessor payment_amount: Float

      attr_accessor payment_currency: String

      attr_accessor payment_currency_code: Integer

      attr_accessor public_id: String

      attr_accessor reason: String

      attr_accessor reason_code: Integer

      attr_accessor refunded: bool

      attr_accessor status: String

      attr_accessor status_code: Integer

      attr_accessor terminal_url: String

      attr_accessor test_mode: bool

      attr_accessor total_fee: Float

      attr_accessor transaction_id: Integer

      attr_accessor type: Integer

      attr_accessor wallet_type: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader auth_code: String?

      def auth_code=: (String) -> String

      attr_reader auth_date: String?

      def auth_date=: (String) -> String

      attr_reader auth_date_iso: String?

      def auth_date_iso=: (String) -> String

      attr_reader card_category: String?

      def card_category=: (String) -> String

      attr_reader card_product: String?

      def card_product=: (String) -> String

      attr_reader confirm_date: String?

      def confirm_date=: (String) -> String

      attr_reader confirm_date_iso: String?

      def confirm_date_iso=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader escrow_accumulation_id: String?

      def escrow_accumulation_id=: (String) -> String

      attr_reader fall_back_scenario_declined_transaction_id: Integer?

      def fall_back_scenario_declined_transaction_id=: (Integer) -> Integer

      attr_reader invoice_id: String?

      def invoice_id=: (String) -> String

      attr_reader ip_city: String?

      def ip_city=: (String) -> String

      attr_reader ip_district: String?

      def ip_district=: (String) -> String

      attr_reader ip_latitude: Float?

      def ip_latitude=: (Float) -> Float

      attr_reader ip_longitude: Float?

      def ip_longitude=: (Float) -> Float

      attr_reader ip_region: String?

      def ip_region=: (String) -> String

      attr_reader json_data: String?

      def json_data=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader original_transaction_id: Integer?

      def original_transaction_id=: (Integer) -> Integer

      attr_reader payout_amount: Float?

      def payout_amount=: (Float) -> Float

      attr_reader payout_date: String?

      def payout_date=: (String) -> String

      attr_reader payout_date_iso: String?

      def payout_date_iso=: (String) -> String

      attr_reader rrn: String?

      def rrn=: (String) -> String

      attr_reader subscription_id: String?

      def subscription_id=: (String) -> String

      attr_reader token: String?

      def token=: (String) -> String

      def initialize: (
        amount: Float,
        android_pay: bool,
        card_exp_date: String,
        card_first_six: String,
        card_holder_message: String,
        card_last_four: String,
        card_type: String,
        card_type_code: Integer,
        created_date: String,
        created_date_iso: String,
        culture_name: String,
        currency: String,
        currency_code: Integer,
        gateway_name: String,
        ip_address: String,
        ip_country: String,
        issuer: String,
        issuer_bank_country: String,
        payment_amount: Float,
        payment_currency: String,
        payment_currency_code: Integer,
        public_id: String,
        reason: String,
        reason_code: Integer,
        refunded: bool,
        status: String,
        status_code: Integer,
        terminal_url: String,
        test_mode: bool,
        total_fee: Float,
        transaction_id: Integer,
        type: Integer,
        wallet_type: String,
        ?account_id: String,
        ?auth_code: String,
        ?auth_date: String,
        ?auth_date_iso: String,
        ?card_category: String,
        ?card_product: String,
        ?confirm_date: String,
        ?confirm_date_iso: String,
        ?description: String,
        ?email: String,
        ?escrow_accumulation_id: String,
        ?fall_back_scenario_declined_transaction_id: Integer,
        ?invoice_id: String,
        ?ip_city: String,
        ?ip_district: String,
        ?ip_latitude: Float,
        ?ip_longitude: Float,
        ?ip_region: String,
        ?json_data: String,
        ?name: String,
        ?original_transaction_id: Integer,
        ?payout_amount: Float,
        ?payout_date: String,
        ?payout_date_iso: String,
        ?rrn: String,
        ?subscription_id: String,
        ?token: String
      ) -> void

      def to_hash: -> {
        amount: Float,
        android_pay: bool,
        card_exp_date: String,
        card_first_six: String,
        card_holder_message: String,
        card_last_four: String,
        card_type: String,
        card_type_code: Integer,
        created_date: String,
        created_date_iso: String,
        culture_name: String,
        currency: String,
        currency_code: Integer,
        gateway_name: String,
        ip_address: String,
        ip_country: String,
        issuer: String,
        issuer_bank_country: String,
        payment_amount: Float,
        payment_currency: String,
        payment_currency_code: Integer,
        public_id: String,
        reason: String,
        reason_code: Integer,
        refunded: bool,
        status: String,
        status_code: Integer,
        terminal_url: String,
        test_mode: bool,
        total_fee: Float,
        transaction_id: Integer,
        type: Integer,
        wallet_type: String,
        account_id: String,
        auth_code: String,
        auth_date: String,
        auth_date_iso: String,
        card_category: String,
        card_product: String,
        confirm_date: String,
        confirm_date_iso: String,
        description: String,
        email: String,
        escrow_accumulation_id: String,
        fall_back_scenario_declined_transaction_id: Integer,
        invoice_id: String,
        ip_city: String,
        ip_district: String,
        ip_latitude: Float,
        ip_longitude: Float,
        ip_region: String,
        json_data: String,
        name: String,
        original_transaction_id: Integer,
        payout_amount: Float,
        payout_date: String,
        payout_date_iso: String,
        rrn: String,
        subscription_id: String,
        token: String
      }
    end
  end
end
