module Cloudpayments
  class PaymentAuthParams = Cloudpayments::Models::PaymentAuthParams

  class PaymentChargeParams = Cloudpayments::Models::PaymentChargeParams

  class PaymentConfirmParams = Cloudpayments::Models::PaymentConfirmParams

  class PaymentPost3dsParams = Cloudpayments::Models::PaymentPost3dsParams

  class PaymentRefundParams = Cloudpayments::Models::PaymentRefundParams

  class PaymentVoidParams = Cloudpayments::Models::PaymentVoidParams
end
