module CloudpaymentsRuby
  module Internal
    extend CloudpaymentsRuby::Internal::Util::SorbetRuntimeSupport

    type file_input =
      Pathname | StringIO | IO | String | CloudpaymentsRuby::FilePart

    OMIT: Object
  end
end
