module CloudpaymentsRuby
  module Resources
    class Payments
      attr_reader tokens: CloudpaymentsRuby::Resources::Payments::Tokens

      def auth: (
        amount: Float,
        card_cryptogram_packet: String,
        ip_address: String,
        ?account_id: String,
        ?culture_name: String,
        ?currency: String,
        ?description: String,
        ?email: String,
        ?invoice_id: String,
        ?json_data: top,
        ?name: String,
        ?payer: CloudpaymentsRuby::PaymentAuthParams::Payer,
        ?payment_url: String,
        ?save_card: bool,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::payment_auth_response

      def charge: (
        amount: Float,
        card_cryptogram_packet: String,
        ip_address: String,
        ?account_id: String,
        ?culture_name: String,
        ?currency: String,
        ?description: String,
        ?email: String,
        ?invoice_id: String,
        ?json_data: top,
        ?name: String,
        ?payer: CloudpaymentsRuby::PaymentChargeParams::Payer,
        ?payment_url: String,
        ?save_card: bool,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::payment_charge_response

      def confirm: (
        amount: Float,
        transaction_id: Integer,
        ?json_data: top,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::PaymentConfirmResponse

      def post3ds: (
        pa_res: String,
        transaction_id: Integer,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::PaymentPost3dsResponse

      def refund: (
        amount: Float,
        transaction_id: Integer,
        ?json_data: top,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::PaymentRefundResponse

      def `void`: (
        transaction_id: Integer,
        ?request_options: CloudpaymentsRuby::request_opts
      ) -> CloudpaymentsRuby::Models::PaymentVoidResponse

      def initialize: (client: CloudpaymentsRuby::Client) -> void
    end
  end
end
